runtime: custom
env: flex
automatic_scaling:
  target_cpu_utilization: 0.95
  min_instances: 1
  max_instances: 1
  min_pending_latency: 500ms
  max_pending_latency: automatic
  max_concurrent_requests: 10
